### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by iamxvbaba** [Big-Fig/Fediverse.app#55]
lib/app/database/dao/remote/app_remote_database_dao.dart:109:18: Error: Type 'GeneratedDateTimeColumn' not found.

**Comment by xal** [comment]
Was related to an invalid moor version. It was 4.4.0(due to bounds in `pubspec.yaml`) but should be 4.2.1. 
Fedi used `moor: ^4.2.1` and now uses `moor: 4.2.1` to fix the issue. In any case, you will have a specified version.
Thanks for contributing
@iamxvbaba Please check your email. I need minor help from you regarding your fork.
